"""AI-assisted analysis."""

import json
import logging
from pathlib import Path

from ai.prompts import RECONSTRUCTION_PROMPT_TEMPLATE, SYSTEM_PROMPT
from ai.provider import ProviderError, analyze_with_fallback
from config.settings import Settings
from intelligence.schema import WebsiteIntelligence

logger = logging.getLogger(__name__)


async def run_ai_analysis(
    intelligence: WebsiteIntelligence,
    settings: Settings,
    output_dir: Path,
) -> dict[str, str]:
    summary = _build_evidence_summary(intelligence)
    user_prompt = f"""Analyze this website intelligence data as an Awwwards creative/motion lead.

Website: {intelligence.url}
Title: {intelligence.title}

Evidence Summary:
{summary}

Answer with evidence-backed sections:
1. Visual identity & color strategy
2. Typography strategy
3. Preloader & page-load choreography
4. Hero & navigation motion
5. Scroll system (scrub/pin/parallax/horizontal)
6. Text/image/video reveals
7. Hover / cursor / micro-interactions
8. Page/section transitions
9. Mobile motion divergence
10. Motion personality & hierarchy
11. Rebuild recommendations (original, not clone)

Mark each finding DETECTED/OBSERVED/INFERRED/ESTIMATED/UNKNOWN.
Never invent GSAP, durations, or easing without evidence.
"""

    if settings.ai_provider == "none" and not _any_api_key(settings):
        return _fallback_interpretation(intelligence)

    try:
        analysis, provider_used = await analyze_with_fallback(
            settings, SYSTEM_PROMPT, user_prompt
        )
        header = f"*Analysis generated by: **{provider_used}***\n\n"
        return {
            "full_analysis": header + analysis,
            "provider_used": provider_used,
            "reconstruction_prompt": _build_reconstruction_prompt(intelligence),
        }
    except ProviderError as exc:
        logger.error("AI analysis failed across all providers: %s", exc)
        fallback = _fallback_interpretation(intelligence)
        fallback["full_analysis"] = (
            f"AI analysis unavailable after trying all configured providers.\n\n{exc}\n\n"
            + fallback["full_analysis"]
        )
        return fallback


def _any_api_key(settings: Settings) -> bool:
    return bool(
        settings.openai_api_key or settings.anthropic_api_key or settings.gemini_api_key
    )


def _build_evidence_summary(intelligence: WebsiteIntelligence) -> str:
    mi = intelligence.motion_intelligence
    data = {
        "pages_analyzed": len(intelligence.pages),
        "technologies": [t.model_dump() for t in intelligence.technologies[:10]],
        "colors": [c.model_dump() for c in intelligence.design_system.colors[:10]],
        "typography": [t.model_dump() for t in intelligence.design_system.typography[:8]],
        "design_direction": intelligence.design_intelligence.design_direction,
        "preloader": mi.preloader.model_dump(mode="json"),
        "page_load_hero": mi.hero_animation,
        "scroll_findings": [f.model_dump(mode="json") for f in mi.scrolltrigger_analysis[:12]],
        "parallax": len(mi.parallax),
        "pinning": len(mi.pinning),
        "horizontal_scroll": len(mi.horizontal_scroll),
        "cursor": mi.cursor.model_dump(mode="json"),
        "gsap_status": mi.gsap_status,
        "scrolltrigger_status": mi.scrolltrigger_status,
        "motion_personality": mi.motion_personality,
        "animations_count": sum(len(p.animations) for p in intelligence.pages),
        "interactions_count": sum(len(p.interactions) for p in intelligence.pages),
    }
    return json.dumps(data, indent=2, default=str)[:10000]


def _build_reconstruction_prompt(intelligence: WebsiteIntelligence) -> str:
    ds = intelligence.design_system
    mi = intelligence.motion_intelligence
    di = intelligence.design_intelligence
    colors = ", ".join(f"{c.role}: {c.value}" for c in ds.colors[:8]) or "Not observed"
    typography = ", ".join(
        f"{t.role}: {t.font_family} {t.font_size}" for t in ds.typography[:6]
    ) or "Not observed"
    tech = ", ".join(f"{t.name} ({t.status})" for t in intelligence.technologies[:8]) or "Unknown"

    return RECONSTRUCTION_PROMPT_TEMPLATE.format(
        design_direction=di.design_direction or "Evidence-based design inferred from analysis",
        layout=json.dumps(ds.grid or ds.containers or {}, default=str)[:500],
        typography=typography,
        colors=colors,
        motion=mi.motion_summary,
        preloader=json.dumps(mi.preloader.model_dump(mode="json"), default=str)[:800],
        page_load=json.dumps(mi.hero_animation, default=str)[:800],
        scroll=json.dumps(
            {
                "findings": len(mi.scrolltrigger_analysis),
                "parallax": len(mi.parallax),
                "pinning": len(mi.pinning),
                "horizontal": len(mi.horizontal_scroll),
                "gsap": mi.gsap_status,
                "scrolltrigger": mi.scrolltrigger_status,
            },
            default=str,
        ),
        interactions=json.dumps(
            {
                "hover_count": len(mi.hover_motion),
                "cursor": mi.cursor.cursor_type,
                "magnetic": mi.cursor.magnetic,
            },
            default=str,
        ),
        mobile=json.dumps(mi.mobile_motion, default=str)[:500],
        technology=tech,
    )


def _fallback_interpretation(intelligence: WebsiteIntelligence) -> dict[str, str]:
    return {
        "full_analysis": (
            "AI analysis not configured. Set AI_PROVIDER and at least one API key in .env.\n\n"
            f"Observed: {len(intelligence.pages)} pages, "
            f"{len(intelligence.technologies)} technologies, "
            f"{len(intelligence.design_system.colors)} colors."
        ),
        "reconstruction_prompt": _build_reconstruction_prompt(intelligence),
    }
