"""AI-assisted analysis."""

import json
import logging
from pathlib import Path

from ai.prompts import RECONSTRUCTION_PROMPT_TEMPLATE, SYSTEM_PROMPT
from ai.provider import ProviderError, analyze_with_fallback
from config.settings import Settings
from intelligence.schema import WebsiteIntelligence

logger = logging.getLogger(__name__)


async def run_ai_analysis(
    intelligence: WebsiteIntelligence,
    settings: Settings,
    output_dir: Path,
) -> dict[str, str]:
    summary = _build_evidence_summary(intelligence)
    user_prompt = f"""Analyze this website intelligence data and provide structured interpretation.

Website: {intelligence.url}
Title: {intelligence.title}

Evidence Summary:
{summary}

Provide sections:
1. Executive Summary
2. Design Direction
3. Motion Design Analysis
4. UX Patterns
5. Rebuild Recommendations

Mark each finding with confidence level (DETECTED/OBSERVED/INFERRED/ESTIMATED/UNKNOWN).
"""

    if settings.ai_provider == "none" and not _any_api_key(settings):
        return _fallback_interpretation(intelligence)

    try:
        analysis, provider_used = await analyze_with_fallback(
            settings, SYSTEM_PROMPT, user_prompt
        )
        header = f"*Analysis generated by: **{provider_used}***\n\n"
        return {
            "full_analysis": header + analysis,
            "provider_used": provider_used,
            "reconstruction_prompt": _build_reconstruction_prompt(intelligence),
        }
    except ProviderError as exc:
        logger.error("AI analysis failed across all providers: %s", exc)
        fallback = _fallback_interpretation(intelligence)
        fallback["full_analysis"] = (
            f"AI analysis unavailable after trying all configured providers.\n\n{exc}\n\n"
            + fallback["full_analysis"]
        )
        return fallback


def _any_api_key(settings: Settings) -> bool:
    return bool(
        settings.openai_api_key or settings.anthropic_api_key or settings.gemini_api_key
    )


def _build_evidence_summary(intelligence: WebsiteIntelligence) -> str:
    data = {
        "pages_analyzed": len(intelligence.pages),
        "technologies": [t.model_dump() for t in intelligence.technologies[:10]],
        "colors": [c.model_dump() for c in intelligence.design_system.colors[:10]],
        "typography": [t.model_dump() for t in intelligence.design_system.typography[:8]],
        "components": [
            c.model_dump()
            for p in intelligence.pages[:3]
            for c in p.components[:5]
        ],
        "animations_count": sum(len(p.animations) for p in intelligence.pages),
        "interactions_count": sum(len(p.interactions) for p in intelligence.pages),
    }
    return json.dumps(data, indent=2, default=str)[:8000]


def _build_reconstruction_prompt(intelligence: WebsiteIntelligence) -> str:
    ds = intelligence.design_system
    colors = ", ".join(c.value for c in ds.colors[:6]) or "Not observed"
    typography = ", ".join(
        f"{t.role}: {t.font_family} {t.font_size}" for t in ds.typography[:6]
    ) or "Not observed"
    components = ", ".join(
        c.name for p in intelligence.pages[:2] for c in p.components
    ) or "Not observed"
    tech = ", ".join(t.name for t in intelligence.technologies[:8]) or "Unknown"

    return RECONSTRUCTION_PROMPT_TEMPLATE.format(
        design_direction="Modern, evidence-based design inferred from analysis",
        layout=json.dumps(ds.grid or ds.containers or {}, default=str)[:500],
        typography=typography,
        colors=colors,
        components=components,
        responsive=json.dumps(intelligence.responsive_system, default=str),
        animations=str(intelligence.motion_system),
        interactions=f"{intelligence.motion_system.get('interaction_count', 0)} interactions observed",
        technology=tech,
        performance="See performance data in JSON evidence",
        accessibility="Follow WCAG guidelines; see accessibility audit",
    )


def _fallback_interpretation(intelligence: WebsiteIntelligence) -> dict[str, str]:
    return {
        "full_analysis": (
            "AI analysis not configured. Set AI_PROVIDER and at least one API key in .env.\n\n"
            f"Observed: {len(intelligence.pages)} pages, "
            f"{len(intelligence.technologies)} technologies, "
            f"{len(intelligence.design_system.colors)} colors."
        ),
        "reconstruction_prompt": _build_reconstruction_prompt(intelligence),
    }
